version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: twoje_haslo
      MYSQL_DATABASE: twoja_baza
      MYSQL_USER: twoj_login
      MYSQL_PASSWORD: twoje_haslo
